version: "3.8"

services:
  mongo:
    build:
      context: ../..
      dockerfile: config/docker/database/Dockerfile
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=solid-todo
      - MONGO_INITDB_ROOT_USERNAME=sekiro
      - MONGO_INITDB_ROOT_PASSWORD=long-arm-centipede
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongo_volume:/data/db

  server:
    build:
      context: ../..
      dockerfile: config/docker/server/Dockerfile
    container_name: server
    restart: always
    environment:
      - ENV=development
      - DB_HOST=mongo
      - DB_USERNAME=todoUser
      - DB_PASSWORD=hakuna-matata-1672
      - DB_DATABASE=solid-todo
    ports:
      - 8000:8000
    volumes:
      - ../..:/usr/code
    depends_on:
      - mongo

volumes:
  mongo_volume:
