version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongo_volume:/data/db

  server:
    build:
      context: ../..
      dockerfile: config/docker/server/Dockerfile
    container_name: server
    restart: always
    environment:
      - ENV=development
      - MONGO_HOST=mongo
      - MONGO_DB=solid-todo
      - MONGO_PORT=27017
    ports:
      - 8000:8000
    volumes:
      - ../..:/usr/code
    depends_on:
      - mongo

volumes:
  mongo_volume:
